spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stockpilot
    username: stockpilot_user
    password: stockpilot_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: stockpilot_user
    password: stockpilot_password
    url: jdbc:postgresql://localhost:5433/stockpilot
    baseline-on-migrate: true
    
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - mappings
          - loggers
  endpoint:
    health:
      show-details: always
